### ISSUE TITLE
Duplicate functionality via Projection API

### ISSUE THREAD

**Issue by ddiakopoulos** [IntelRealSense/realsense_sdk#1]
https://github.com/IntelRealSense/realsense_sdk/blob/master/sdk/src/samples/projection_sample/projection_sample.cpp and related Projection API (UV map / inverse UV map) are all already implemented fully within librealsense: https://github.com/IntelRealSense/librealsense/blob/master/include/librealsense/rs.hpp#L24

**Comment by oordan** [comment]
functional partition is set. projection is SDK functionality. will be more clear in librealsense 2.
