### ISSUE TITLE
getting compilation error: enumeration value ‘distortion_ftheta’ not handled in switch

### ISSUE THREAD

**Issue by shomedas** [IntelRealSense/realsense_sdk#13]
I get error while compiling. I am using ubuntu 16.06,64bit. I have installed librealsense-master, opencv 3.1, libog4cxx10v5, liblog4cxx10-dev, liblog4cxx-dev

desktop:~/softwares/sensor-drivers/realsense_sdk/build$ make -j8
Scanning dependencies of target rs_compression
Scanning dependencies of target rs_log_utils
Scanning dependencies of target rs_logger
Scanning dependencies of target rs_fps_utils
Scanning dependencies of target rs_cl_util
[  1%] Building CXX object sdk/src/cameras/compression/CMakeFiles/rs_compression.dir/compression_mock.cpp.o
[  3%] Building CXX object sdk/src/utilities/fps/CMakeFiles/rs_fps_utils.dir/fps_utils.cpp.o
[  5%] Building CXX object sdk/src/utilities/logger/logger/CMakeFiles/rs_logger.dir/xlevel.cpp.o
[  7%] Building CXX object sdk/src/utilities/command_line/CMakeFiles/rs_cl_util.dir/cmd_base.cpp.o
[  8%] Building CXX object sdk/src/utilities/logger/logger/CMakeFiles/rs_logger.dir/logger.cpp.o
[ 10%] Building CXX object sdk/src/utilities/command_line/CMakeFiles/rs_cl_util.dir/basic_cmd_util.cpp.o
[ 12%] Building CXX object sdk/src/utilities/logger/log_utils/CMakeFiles/rs_log_utils.dir/log_utils.cpp.o
In file included from /home/krr/softwares/sensor-drivers/realsense_sdk/sdk/src/utilities/image/librealsense_image_utils.h:2:0,
                 from /home/krr/softwares/sensor-drivers/realsense_sdk/sdk/src/cameras/include/file_types.h:7,
                 from /home/krr/softwares/sensor-drivers/realsense_sdk/sdk/src/cameras/compression/compression_interface.h:9,
                 from /home/krr/softwares/sensor-drivers/realsense_sdk/sdk/src/cameras/compression/compression_mock.h:5,
                 from /home/krr/softwares/sensor-drivers/realsense_sdk/sdk/src/cameras/compression/compression_mock.cpp:1:
/home/krr/softwares/sensor-drivers/realsense_sdk/sdk/include/rs/utils/librealsense_conversion_utils.h: In function ‘rs::core::distortion_type rs::utils::convert_distortion(rs::distortion)’:
/home/krr/softwares/sensor-drivers/realsense_sdk/sdk/include/rs/utils/librealsense_conversion_utils.h:101:19: error: **enumeration value ‘distortion_ftheta’ not handled in switch [-Werror=switch]**
             switch(lrs_distortion)
                   ^
In file included from /home/krr/softwares/sensor-drivers/realsense_sdk/sdk/src/cameras/compression/compression_interface.h:9:0,
                 from /home/krr/softwares/sensor-drivers/realsense_sdk/sdk/src/cameras/compression/compression_mock.h:5,
                 from /home/krr/softwares/sensor-drivers/realsense_sdk/sdk/src/cameras/compression/compression_mock.cpp:1:
/home/krr/softwares/sensor-drivers/realsense_sdk/sdk/src/cameras/include/file_types.h: In constructor ‘rs::core::file_types::frame_sample::frame_sample(rs_stream, rs_frame_ref_, uint64_t)’:
/home/krr/softwares/sensor-drivers/realsense_sdk/sdk/src/cameras/include/file_types.h:157:43: error: ‘rs_frame_ref {aka struct rs_frame_ref}’ has no member named ‘get_frame_stride_x’
                     finfo.stride_x = ref->get_frame_stride_x();
                                           ^
/home/krr/softwares/sensor-drivers/realsense_sdk/sdk/src/cameras/include/file_types.h:158:43: error: ‘rs_frame_ref {aka struct rs_frame_ref}’ has no member named ‘get_frame_stride_y’
                     finfo.stride_y = ref->get_frame_stride_y();
                                           ^
[ 14%] Linking CXX shared library ../../../../../sdk/lib/release/librs_fps_utils.so
cc1plus: all warnings being treated as errors
sdk/src/cameras/compression/CMakeFiles/rs_compression.dir/build.make:62: recipe for target 'sdk/src/cameras/compression/CMakeFiles/rs_compression.dir/compression_mock.cpp.o' failed
make[2]: *_\* [sdk/src/cameras/compression/CMakeFiles/rs_compression.dir/compression_mock.cpp.o] Error 1
CMakeFiles/Makefile2:791: recipe for target 'sdk/src/cameras/compression/CMakeFiles/rs_compression.dir/all' failed
make[1]: **\* [sdk/src/cameras/compression/CMakeFiles/rs_compression.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
[ 14%] Built target rs_fps_utils
[ 16%] Linking CXX shared library ../../../../../../sdk/lib/release/librs_log_utils.so
[ 17%] Linking CXX shared library ../../../../../../sdk/lib/release/librs_logger.so
[ 17%] Built target rs_log_utils
[ 17%] Built target rs_logger
[ 19%] Linking CXX static library ../../../../../sdk/lib/release/librs_cl_util.a
[ 19%] Built target rs_cl_util
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by oordan** [comment]
It looks like a mismatch between the SDK version and librealsense version. Please make sure you are using librealsense 1.9.4 (which is not the latest on github).

**Comment by EldarZ** [comment]
hi @shomedas, 
did you manage to compile? can we close this?
