### ISSUE TITLE
Unusual target location  

### ISSUE THREAD

**Issue by halton** [IntelRealSense/realsense_sdk#15]
Follow the common cmake build steps, `mkdir build; cd build; cmake ..; make`, the below out libraries and binaries are not located under `build`,  instead located at src directory.
```
sdk/bin/debug/*
sdk/bin/release/*
sdk/lib/debug/*
sdk/lib/release/*
samples/bin/debug/*
samples/bin/release/*
tests/bin/*
```

There are two issues I file this issues:
*  Code tree is dirty (although ,gitignore hide them). One of benefit Cmake vs Makefile is code and build directory are de-coupled. Which make developer to re-use one code tree with multiple configurations. 
* CMake users normally suppose all generated files(Makefile, etc), libraries and binaries are located under build dir,

**Comment by Bolshem** [comment]
Hi Halton.

Thank you for reporting the issue and for the pull request. 
I am working on it now, and will commit as soon as possible...

**Comment by halton** [comment]
@Bolshem any followup?
