### ISSUE TITLE
Broken pdf documents under sdk/doc

### ISSUE THREAD

**Issue by halton** [IntelRealSense/realsense_sdk#18]
When I checkout latest code, I failed to open the `Developer Guide.pdf` and `Getting Started Guide.pdf` via Evince or Google Chrome, seems those two pdf are broken.

**Comment by aeskenas** [comment]
Hi,
Sorry for the late response.
Files were removed in latest release (0.7.1) and will be added once we will have files in the final format supported.
Thanks for your response!
