### ISSUE TITLE
Confusing type re-definition

### ISSUE THREAD

**Issue by ddiakopoulos** [IntelRealSense/realsense_sdk#2]
rs::core::pixel_format - as found in places like this https://github.com/IntelRealSense/realsense_sdk/blob/master/sdk/include/rs/utils/librealsense_conversion_utils.h

There is a 1:1 mapping between `realsense_sdk` and `librealsense`. Since `librealsense` is a dependency of this repo, why not use those types directly instead of creating a translation layer?

**Comment by oordan** [comment]
Fixed some issues in SDK components consumed by MWs, to become independent of librealsense.
We also cleaned unused definitions, which were redefined but not used.
