### ISSUE TITLE
Compile Error 

### ISSUE THREAD

**Issue by Briam9173** [IntelRealSense/realsense_sdk#21]
I am trying to build the realsense sdk in ubuntu 16.04. And I have installed opencv 3.1. When I compiled the sdk, here were some error. How can I solve this problem? Thank you.

![image](https://cloud.githubusercontent.com/assets/20610259/24737034/bc62ea54-1ac6-11e7-847a-de0cae62960c.png)

**Comment by zivsha** [comment]
Hi @Briam9173,

Have you followed [these instructions](https://software.intel.com/sites/products/realsense/sdk/developer_guide.html#Compiling_the_SDK)?

From the compiler error message it seems that projection_tool (which depends on opencv) is looking for  opencv's libraries that contain the implementation of (for instance) deallocate(), but it can't find these libraries.
Perhaps you forgot to "make install" opencv?
I suggest following [this guid](http://embedonix.com/articles/image-processing/installing-opencv-3-1-0-on-ubuntu/) to properly install opencv on Ubuntu

**Comment by Briam9173** [comment]
I tried to re-install opencv3.1 and build the sdk again but the problem can't solve. 

![image](https://cloud.githubusercontent.com/assets/20610259/24745985/85da43f2-1af2-11e7-8247-faeb40b20ec5.png)

I am trying to install a new ubuntu and re-build opencv and sdk.

**Comment by Briam9173** [comment]
Thank you. I have installed new linux and re-build the sdk. All problem were solved.
