### ISSUE TITLE
Compilation error: librealsense/rs.hpp: No such file or directory

### ISSUE THREAD

**Issue by mkatliar** [IntelRealSense/realsense_sdk#23]
Building `librealsense` from `master` branch using following commands:
```bash
mkdir build
cd build
make -j 4
```
Produces output:
```
/home/kotlyar/software/realsense_sdk/samples/src/fps_counter_sample/main.cpp:10:31: fatal error: librealsense/rs.hpp: No such file or directory
 #include <librealsense/rs.hpp>
                               ^
compilation terminated.
```
There is no file named "rs.hpp" in the source tree.

**Comment by mkatliar** [comment]
My mistake; confused the `realsense_sdk` and `librealsense` projects.

**Comment by wangzhaoguang** [comment]
did you solve it ?

**Comment by arixrobotics** [comment]
@wangzhaoguang try this https://github.com/stevenlovegrove/Pangolin/pull/190/commits/ce7ded2a0701609401b9f9df308d12540e6891a7
