### ISSUE TITLE
OpenCV is a depencency, but its presence not checked by the CMake scripts?

### ISSUE THREAD

**Issue by mkatliar** [IntelRealSense/realsense_sdk#24]
Building `realsense_sdk` from `master` branch using following commands:
```bash
mkdir build
cd build
make -j 4
```
produces the following compiler error on my system:
```
/home/kotlyar/software/realsense_sdk/sdk/src/core/image/image_conversion_util.cpp:7:23: fatal error: opencv/cv.h: No such file or directory
 #include "opencv/cv.h"
                       ^
compilation terminated.
```
Apparently `image_conversion_util.cpp` requires `OpenCV` which is not installed, but the `CMake` scripts don't check for it.

**Comment by zivsha** [comment]
Hi @mkotlyar ,

Thanks for bringing this to our attention, our CMake script indeed does not enforce all dependencies and OpenCV in particular.
Please find the SDK's dependencies list here: https://github.com/IntelRealSense/realsense_sdk#dependencies-list
