### ISSUE TITLE
OpenCV: Modifications to CMakeLists.txt Seems to be Required

### ISSUE THREAD

**Issue by ckfourie** [IntelRealSense/realsense_sdk#27]
Ubuntu 16.04, OpenCV 3.2 

Had to modify all the CMakeLists.txt files to allow compilation. Otherwise got a lot of undefined references (think because I'm using OpenCV 3.2). Modifications were essentially, 

`find_package(OpenCV 3.1 REQUIRED)` 
`...`
`target_link_libraries(... ${OpenCV_LIBRARIES})` 

for all the CMakeLists.txt

Appears to be working fine otherwise. Was there a reason for limiting the library to OpenCV 3.1?

**Comment by zivsha** [comment]
Hi, 
Sorry for responding so late.
CMake files are indeed missing the `find_package` macro, if a new release comes out this will be incorporated.
OpenCV 3.1 was chosen to meet Intel's middlewares (computer vision modules) requirements.
